from __future__ import annotations

import argparse
import json
import sqlite3
from collections.abc import Iterable, Sequence
from pathlib import Path
from typing import Final

TABLES_IN_DELETE_ORDER: Final[tuple[str, ...]] = (
    "telegram_delivery",
    "last_rule_state",
    "alert_event",
    "price_observation",
    "source_mapping",
    "instrument",
)


def sql_literal(value: object) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, int):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def rows(connection: sqlite3.Connection, query: str) -> Iterable[Sequence[object]]:
    return connection.execute(query).fetchall()


def insert_statements(
    table: str, columns: Sequence[str], values: Iterable[Sequence[object]]
) -> list[str]:
    column_list = ",".join(columns)
    return [
        f"INSERT INTO {table}({column_list}) VALUES("
        f"{','.join(sql_literal(value) for value in row)});"
        for row in values
    ]


def table_exists(connection: sqlite3.Connection, table: str) -> bool:
    return (
        connection.execute(
            "SELECT 1 FROM sqlite_master WHERE type='table' AND name=?", (table,)
        ).fetchone()
        is not None
    )


def export_database(source: Path) -> str:
    connection = sqlite3.connect(f"file:{source}?mode=ro", uri=True)
    try:
        required = {
            "instrument",
            "sourcemapping",
            "priceobservation",
            "alertevent",
            "lastrulestate",
            "telegramdelivery",
        }
        missing = sorted(table for table in required if not table_exists(connection, table))
        if missing:
            raise ValueError(f"SQLite database is missing tables: {', '.join(missing)}")

        output = [
            "-- Generated by worker/scripts/export_sqlite_to_d1.py.",
            "-- Apply worker/migrations first, then execute this file once.",
            "PRAGMA foreign_keys = ON;",
        ]
        output.extend(f"DELETE FROM {table};" for table in TABLES_IN_DELETE_ORDER)
        output.extend(
            insert_statements(
                "instrument",
                (
                    "id",
                    "name",
                    "enabled",
                    "alert_mode",
                    "supports",
                    "resistances",
                    "high_water",
                    "fixed_drawdown",
                    "near_support_threshold",
                    "risk_reward_threshold",
                    "created_at",
                    "updated_at",
                    "rule_cycle_started_at",
                ),
                rows(
                    connection,
                    "SELECT id,name,enabled,alert_mode,supports,resistances,"
                    "CAST(high_water AS TEXT),CAST(fixed_drawdown AS TEXT),"
                    "CAST(near_support_threshold AS TEXT),CAST(risk_reward_threshold AS TEXT),"
                    "created_at,updated_at,rule_cycle_started_at FROM instrument ORDER BY id",
                ),
            )
        )
        output.extend(
            insert_statements(
                "source_mapping",
                ("id", "instrument_id", "provider", "market_type", "symbol", "enabled"),
                rows(
                    connection,
                    "SELECT id,instrument_id,provider,market_type,symbol,enabled "
                    "FROM sourcemapping ORDER BY id",
                ),
            )
        )
        output.extend(
            insert_statements(
                "price_observation",
                ("id", "source_mapping_id", "price", "observed_at", "raw_path", "error"),
                rows(
                    connection,
                    "SELECT id,source_mapping_id,CAST(price AS TEXT),observed_at,"
                    "raw_path,error FROM priceobservation ORDER BY id",
                ),
            )
        )
        output.extend(
            insert_statements(
                "alert_event",
                (
                    "id",
                    "instrument_id",
                    "source_mapping_id",
                    "alert_kind",
                    "price",
                    "support",
                    "resistance",
                    "threshold",
                    "message",
                    "triggered_at",
                    "rule_cycle_started_at",
                ),
                rows(
                    connection,
                    "SELECT id,instrument_id,source_mapping_id,alert_kind,CAST(price AS TEXT),"
                    "CAST(support AS TEXT),CAST(resistance AS TEXT),CAST(threshold AS TEXT),"
                    "message,triggered_at,rule_cycle_started_at FROM alertevent ORDER BY id",
                ),
            )
        )
        output.extend(
            insert_statements(
                "last_rule_state",
                (
                    "instrument_id",
                    "source_mapping_id",
                    "last_price",
                    "near_support_active",
                    "risk_reward_active",
                    "above_resistance_active",
                    "support_breach_active",
                    "near_support_last_alert_at",
                    "risk_reward_last_alert_at",
                    "breakout_last_alert_at",
                    "support_breach_last_alert_at",
                    "last_invalid_state",
                    "updated_at",
                ),
                rows(
                    connection,
                    "SELECT instrument_id,source_mapping_id,CAST(last_price AS TEXT),"
                    "near_support_active,risk_reward_active,above_resistance_active,"
                    "support_breach_active,near_support_last_alert_at,risk_reward_last_alert_at,"
                    "breakout_last_alert_at,support_breach_last_alert_at,"
                    "last_invalid_state,updated_at "
                    "FROM lastrulestate ORDER BY instrument_id,source_mapping_id",
                ),
            )
        )
        output.extend(
            insert_statements(
                "telegram_delivery",
                (
                    "id",
                    "status",
                    "message_kind",
                    "message_text",
                    "chat_ref",
                    "telegram_message_id",
                    "safe_error",
                    "delivered_at",
                ),
                rows(
                    connection,
                    "SELECT id,status,message_kind,message_text,chat_ref,telegram_message_id,"
                    "safe_error,delivered_at FROM telegramdelivery ORDER BY id",
                ),
            )
        )
        output.append(
            "UPDATE runtime_state SET scheduler_ready=0,providers_ready=0,"
            "enabled_sources=0,polled_sources=0,observations_written=0,"
            "source_errors=0,alert_events_created=0,telegram_deliveries_attempted=0,"
            "last_tick_started_at=NULL,last_tick_finished_at=NULL WHERE singleton=1;"
        )
        return "\n".join(output) + "\n"
    finally:
        connection.close()


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Export the current WaveMonitor SQLite schema as D1 SQL."
    )
    parser.add_argument("source", type=Path, help="Path to wavemonitor.sqlite3")
    parser.add_argument("output", type=Path, help="Destination SQL file")
    args = parser.parse_args()
    if not args.source.is_file():
        parser.error(f"source database does not exist: {args.source}")
    args.output.write_text(export_database(args.source), encoding="utf-8")
    print(json.dumps({"source": str(args.source), "output": str(args.output)}))


if __name__ == "__main__":
    main()
